/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'

import PageHeading from '/components/page-heading'
import GridList from '/components/grid-list'
import { getDeepDives } from '/lib/getData'

const data = getDeepDives()

export default function Home() {
  return (
    <div>
      <Head>
        <title>Deep dives | Better Dev Screencasts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeading title="Deep dives">
        <p>Hold your breath... We're going down a rabbit hole, and we're going deep.</p>
      </PageHeading>
      <GridList data={data} />
    </div>
  )
}
