import Head from 'next/head'

import PageHeading from '/components/page-heading'
import GridList from '/components/grid-list'
import { getHotTips } from '/lib/getData'

const data = getHotTips()

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hot Tips | Better Dev Screencasts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeading title="Hot tips">
        <p>Short, but effective tips to take your video production to the next level!</p>
      </PageHeading>
      <GridList data={data} />
    </div>
  )
}
