import Head from 'next/head'

import PageHeading from '/components/page-heading'
import GridList from '/components/grid-list'
import { getAllFiles } from '/lib/getData'

const data = getAllFiles()

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeading title="Helping developers create better screencasts">
        <p>
          A collection of resources to help developers create better screencasts, and level-up their
          overall video content creation game.
        </p>
      </PageHeading>
      <GridList data={data} showCategory />
    </>
  )
}
