import Head from 'next/head'

import PageHeading from '/components/page-heading'
import GridList from '/components/grid-list'
import { getVideos } from '/lib/getData'

const data = getVideos()

export default function Home() {
  return (
    <div>
      <Head>
        <title>Videos | Better Dev Screencasts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeading title="Videos">
        <p>They say an image is worth a thousand words... That means a video is worth.. a lot!</p>
      </PageHeading>
      <GridList data={data} />
    </div>
  )
}
